# Generated by Django 3.1.7 on 2021-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="document_file",
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_text",
        ),
        migrations.RemoveField(
            model_name="document",
            name="person",
        ),
        migrations.AddField(
            model_name="document",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/covers/"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="fichier",
            field=models.FileField(null=True, upload_to="documents/fichiers"),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
