# Generated by Django 3.1.7 on 2021-02-26 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_auto_20210226_1750"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=100, null=True)),
                ("last_name", models.CharField(default="", max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="person",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="uploads.person",
            ),
        ),
    ]
