# Generated by Django 3.1.7 on 2021-03-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0003_auto_20210226_1841"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonModel",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="uploads.person",
                    ),
                ),
                ("id_person", models.UUIDField()),
            ],
            bases=("uploads.person",),
        ),
        migrations.RemoveField(
            model_name="document",
            name="author",
        ),
        migrations.RemoveField(
            model_name="document",
            name="cover",
        ),
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
