# Generated by Django 3.1.7 on 2021-03-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_auto_20210301_1434"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="File",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="fichier",
            new_name="content_file",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="title",
            new_name="title_file",
        ),
    ]
