# Generated by Django 3.1.7 on 2021-03-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0005_auto_20210301_1512"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personmodel",
            old_name="id_person",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="file",
            name="person",
        ),
        migrations.AddField(
            model_name="person",
            name="file",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="uploads.file",
            ),
        ),
    ]
