# Generated by Django 3.1.7 on 2021-03-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0006_auto_20210301_1830"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="content_file",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="person",
            name="file",
        ),
        migrations.AddField(
            model_name="file",
            name="person",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="uploads.person",
            ),
        ),
    ]
