# Generated by Django 3.1.7 on 2021-03-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0007_auto_20210301_1843"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file",
            new_name="content_file",
        ),
    ]
