# Generated by Django 3.1.7 on 2021-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0009_remove_personmodel_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonModel",
        ),
    ]
