# Generated by Django 3.1.7 on 2021-03-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0011_personmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonModel",
        ),
    ]
