# Generated by Django 3.1.7 on 2021-03-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0012_delete_personmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="title_file",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="file",
            name="content_file",
        ),
        migrations.AddField(
            model_name="file",
            name="content",
            field=models.FileField(default=None, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="file",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="uploads.person"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
